name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: alskipp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-shell --run "cabal test"
